# Generated by Django 6.0.3 on 2026-05-04 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "universities",
            "0009_university_course_type_university_institution_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opening_datetime", models.DateTimeField()),
                ("info_link", models.URLField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission_openings",
                        to="universities.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admission Opening",
                "verbose_name_plural": "Admission Openings",
                "ordering": ["opening_datetime"],
            },
        ),
    ]
