from django.urls import path
from . import views

app_name = 'custom_admin'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('add/', views.add_university, name='add_university'),
    path('edit/<int:pk>/', views.edit_university, name='edit_university'),
    path('delete/<int:pk>/', views.delete_university, name='delete_university'),
    path('users/', views.manage_users, name='manage_users'),
    path('users/delete/<int:user_id>/', views.delete_student, name='delete_student'),
    path('upload-csv/', views.upload_universities_csv, name='upload_csv'),
    path('departments/', views.manage_departments, name='manage_departments'),
    path('departments/add/', views.add_department, name='add_department'),
    path('departments/edit/<int:pk>/', views.edit_department, name='edit_department'),
    path('departments/delete/<int:pk>/', views.delete_department, name='delete_department'),
    path('events/', views.manage_events, name='manage_events'),
    path('events/add/', views.add_event, name='add_event'),
    path('events/edit/<int:pk>/', views.edit_event, name='edit_event'),
    path('events/delete/<int:pk>/', views.delete_event, name='delete_event'),
    path('scholarships/', views.manage_scholarships, name='manage_scholarships'),
    path('scholarships/add/', views.add_scholarship, name='add_scholarship'),
    path('scholarships/edit/<int:pk>/', views.edit_scholarship, name='edit_scholarship'),
    path('scholarships/delete/<int:pk>/', views.delete_scholarship, name='delete_scholarship'),
    path('faq-categories/', views.manage_faq_categories, name='manage_faq_categories'),
    path('faq-categories/add/', views.add_faq_category, name='add_faq_category'),
    path('faq-categories/edit/<int:pk>/', views.edit_faq_category, name='edit_faq_category'),
    path('faq-categories/delete/<int:pk>/', views.delete_faq_category, name='delete_faq_category'),
    path('faqs/', views.manage_faq_items, name='manage_faq'),
    path('faqs/add/', views.add_faq_item, name='add_faq_item'),
    path('faqs/edit/<int:pk>/', views.edit_faq_item, name='edit_faq_item'),
    path('faqs/delete/<int:pk>/', views.delete_faq_item, name='delete_faq_item'),
    path('clubs/', views.manage_clubs, name='manage_clubs'),
    path('clubs/add/', views.add_club, name='add_club'),
    path('clubs/edit/<int:pk>/', views.edit_club, name='edit_club'),
    path('clubs/delete/<int:pk>/', views.delete_club, name='delete_club'),
    path('admissions/', views.manage_admissions, name='manage_admissions'),
    path('admissions/add/', views.add_admission, name='add_admission'),
    path('admissions/edit/<int:pk>/', views.edit_admission, name='edit_admission'),
    path('admissions/delete/<int:pk>/', views.delete_admission, name='delete_admission'),
]
