# Generated by Django 6.0.5 on 2026-05-10 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0012_scholarship_and_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_hostel_service', models.BooleanField(default=False)),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='universities.university')),
            ],
        ),
    ]
