# Generated by Django 6.0.4 on 2026-05-04 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0009_university_course_type_university_institution_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='universities.university')),
            ],
            options={
                'verbose_name_plural': 'Clubs',
                'ordering': ['name'],
            },
        ),
    ]
