# Generated by Django 6.0.3 on 2026-04-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.URLField(blank=True, help_text='Enter image URL (e.g., from Unsplash)', max_length=500, null=True),
        ),
    ]
