# Generated by Django 6.0.3 on 2026-04-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_alter_university_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload university image', null=True, upload_to='universities/'),
        ),
    ]
