# Generated by Django 6.0.3 on 2026-04-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_alter_university_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='google_maps_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
