# Generated by Django 6.0.3 on 2026-04-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_university_google_maps_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='close_credit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='open_credit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
