# Generated by Django 6.0.3 on 2026-04-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_university_close_credit_university_open_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='close_credit',
        ),
        migrations.RemoveField(
            model_name='university',
            name='open_credit',
        ),
        migrations.AddField(
            model_name='university',
            name='credit_system',
            field=models.CharField(blank=True, choices=[('Open', 'Open Credit'), ('Closed', 'Closed Credit')], max_length=10, null=True),
        ),
    ]
