# Generated by Django 6.0.3 on 2026-04-30 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_remove_university_close_credit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_level', models.CharField(help_text="e.g., Bachelor's Fall 2026", max_length=100)),
                ('deadline', models.DateField()),
                ('apply_link', models.URLField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='universities.university')),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(help_text='e.g., Main Auditorium or Zoom Link', max_length=200)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='universities.university')),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
