# Generated by Django 6.0.3 on 2026-04-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_admission_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='short_name',
            field=models.CharField(blank=True, help_text='e.g., BUET,BRACU,NSU,AIUB, UAP', max_length=50, null=True),
        ),
    ]
