# Generated by Django 6.0.3 on 2026-05-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0008_university_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='course_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='institution_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='subject_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
