# Generated by Django 6.0.3 on 2026-05-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0010_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for this department', null=True, upload_to='departments/'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional banner or poster image', null=True, upload_to='events/'),
        ),
    ]
