# Generated by Django 6.0.3 on 2026-05-04 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0011_department_event_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'FAQ categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='universities.faqcategory')),
            ],
            options={
                'verbose_name_plural': 'FAQ items',
                'ordering': ['category', 'sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='Short highlight (e.g. "Up to 100% tuition")', max_length=300)),
                ('description', models.TextField()),
                ('deadline', models.DateField(blank=True, help_text='Optional application deadline', null=True)),
                ('apply_link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in the home page “Featured scholarships” strip')),
                ('image', models.ImageField(blank=True, null=True, upload_to='scholarships/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='universities.university')),
            ],
            options={
                'verbose_name_plural': 'Scholarships',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
